### ISSUE TITLE
Screen Flicker

### ISSUE THREAD

**Issue by aka5hkumar** [veyon/veyon#83]
Just rolled Veyon out onto a bunch of new Windows 10 installations, and the screens are flickering. Did not have this issue with italc in windows 7.

Dell Precision Tower 7810
Xeon E5-2603 v3
Windows 10 Enterprise
Nvidia Quadro K2200
1920x1080 screens over display port 

[blink.json.txt](https://github.com/veyon/veyon/files/1220083/blink.json.txt)

Specifically seen in task manager or in System Information.

**Comment by tobydox** [comment]
Do the screens flicker locally or in remote view? Which parts do flicker?

**Comment by MySagona** [comment]
I have seen the same behavior.  For me, it only only occurs in application windows I am running as another user, and it only occurs while the Veyon Master is running.  If I close Veyon Master, the flicker goes away.  If I am running an application using the same user account that I am logged into, those application windows do not flicker.

**Comment by edanpedragosa** [comment]
Hi! I'm seeing this behavior as well. It seems like all the windows refreshes every second when VEYON Master is running. Terminating VEYON Master stops the flickering/refresh effect.

**Comment by Fiala06** [comment]
Having the same issue.

**Comment by Lieven-T** [comment]
I have an issue that could very well be related to this. I have a bit extra information: I had the 'find cursus when CTRL key is pressed' enabled on a test PC, and during the flicker, the sonar thing appears around my cursor as if the CTRL was being pressed. About once a second, following things happen:
- CTRL key is pressed
- Caps lock gets disabled when enabled
- If a context menu is opened, it is closed

I do notice a slight flicker in some windows (e.g. the winver screen flickered slightly). This happened in between the 'sonar pulses'.

This only happens when Veyon Master is triggered, Win10 1709 release, 64 bit OS and Veyon installation.

**Comment by jmartins1** [comment]
Possibly related. On Windows 10, when master is running it will cause a problem with client computers. Veyon will turn the Caps lock on and off causing longing issues as well as topping once logged in.

**Comment by gabrielmsilveira** [comment]
I installed version 4.0.4 Master on some computers to monitor a lab. And I noticed the same problem, the caps lock key turns off or on by itself and the shift is disabled by itself. But the Veyon Master is back to normal. Which version solved this problem?

**Comment by jmartins1** [comment]
Unfortunately, I just uninstalled it. It was unusable. I'll try again in the future maybe they'll have it fixed by then.

⁣Sent from BlueMail ​

**Comment by scrfc71** [comment]
same problem here.
Monitor is flickering during Master is running. When master process is killed, everything is okay.

Any updates on fixing or working workarounds?

**Comment by ceastland** [comment]
I have the same problem.  The caps lock bug is a biggie and requires keeping master closed.  not very usefull that way...

**Comment by tobydox** [comment]
The caps lock issue has been fixed and will be part of upcoming 4.1.6 release. Regarding the screen flicker issue we do not have a solution yet. Here some application only flicker for a very short period (0.5 sec?) right after starting Veyon Master. However everybody is invited to try the latest releases. Version 4.1.3 and newer integrate the new DeskDupEngine from the UltraVNC project which could improve things on Windows 10.

**Comment by scrfc71** [comment]
Any updates here?

**Comment by MacGyverTheMan** [comment]
Same issue on a brand new install.  With the master open, all open windows flicker every 1-2 seconds, becoming very difficult to use.  Any updates to this?

**Comment by Eruthon** [comment]
On version 4.4.2 it's still an issue; I also had the Ctrl key circle animation arround the cursor turned on and it was doing it every second or so, on mutiple PCs when Veyon Master was opened. That's why the Ctrl key wasn't recognized sometimes imo.

**Comment by geoffreycastillo** [comment]
Same problem in 4.4.2.

There's a simple test: press ALT+TAB and maintain ALT. The 'alt-tab switcher' goes away. If the 'Thumbnail update interval' is set to 1 second, this happens after 1 second; if set to 5, after 5 seconds; etc.

Disabling the Desktop Duplication Engine or the Poll full screen doesn't change anything.

I think #561 is the same problem.

**Comment by SlrG** [comment]
I don't know, if this is helpful, but in the previous days I had a room with Windows 10 in our school, where on the teacher pc there was massive screen flicker in other software windows and especially system dialogue, when the master software was running. Maybe this is/was the same flicker mentioned here?

Also the student PCs were not accessible and in the master authentication errors were reported. The reason was, that the public key file was missing on the student PCs. We have system images, that we distribute to PCs and which are used to reset the systems to their default state on each boot.

After fixing the student image and adding the public key file, the authentication errors were solved and the screen flicker was gone, too!

So maybe the flicker is caused by authentication errors in your Veyon installations? Maybe the developers could check what could cause the flicker when an authentication error occurs? 

Maybe it has to do with the dialogue which can be displayed whenever someone is trying to access a PC without the necessary access rights? We have this disabled by default, but I noticed when enabled, the flicker and the refresh of the dialogue happen at the same time.
